apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-agent
spec:
  template:
    spec:
      containers:
      - name: ci-cd-agent
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "1000m"
            ephemeral-storage: "2Gi"
