apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: DevOps AI Agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bshongwe/devops-ai-agent.git
    targetRevision: HEAD
    path: staging/https-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true