apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e2e-customer-churn-prediction-mlflow-dvc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bshongwe/e-2-2-customer-churn-prediction-MLflow-DVC.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true