apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-agent
spec:
  template:
    spec:
      containers:
      - name: ci-cd-agent
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
